#!/usr/bin/python
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "lib.settings")
import django
from models.dao import DatabaseHandler


def main():
    dbh = DatabaseHandler()
    #phrases = dbh.get_phrases()
    p = dbh.get_phrase_by_id(138)
    print p
    
if __name__ == '__main__':
    main()
