#!/usr/bin/env python
import subprocess
import os
import re
import json
import operator
import sys
import math
from config.config import Config as MuspracticeConfig


CONFIG_FILENAME = '.muspractice_tag_weights'
LOCAL_CONFIG_FILENAME = '%s/%s' % (os.getcwd(), CONFIG_FILENAME)
GLOBAL_CONFIG_FILENAME = '%s/%s' % (os.environ['HOME'], CONFIG_FILENAME)

def get_config_path():
    """
    Find appropriate config file with target tag weights. Local file
    in the current directory will override the global file in home
    directory.

    Filenames:
    - .muspractice_tag_weights (current working directory)
    - ~/.muspractice_tag_weights (global)
    """
    if len(sys.argv) > 1:
        return sys.argv[1]

    if os.path.exists(LOCAL_CONFIG_FILENAME):
        return LOCAL_CONFIG_FILENAME
    elif os.path.exists(GLOBAL_CONFIG_FILENAME):
        return GLOBAL_CONFIG_FILENAME
    return None

def get_config():
    """Read target weights from config file"""
    config_file = get_config_path()
    if not config_file or not os.path.exists(config_file):
        raise RuntimeError('Could not find tag weight config: %s' % (config_file))
    with open(config_file, 'r') as inp:
        config_dict = json.load(inp)

    # check that total sum of all weights is 1.0 (for consistent results)
    weight_sum = 0
    for tag in config_dict['tag_weights'].keys():
        weight_sum += config_dict['tag_weights'][tag]

    if abs(weight_sum - 1.0) > 0.001:
        print('The sum of all target weights in config file %s should be 1.0. Current sum: %f. Please adjust the target weights.' % (config_file, weight_sum))
        sys.exit(1)
    return config_dict

CONFIG = get_config()

def get_data():
    """Read repetition data from muspractice"""
    muspractice_config = MuspracticeConfig()
    cmd = "python muspractice -d %s -R | tail -n %s" % (muspractice_config.DATABASE_FILE, CONFIG['history_length'])
    popen = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = popen.communicate()
    result = []
    for line in stdout.splitlines():
        tagline = line.split(':::')[-2]
        tagline = re.sub(' +', ' ', tagline)
        tags = tagline.split(' ')
        result.append(tags)
    return result

def get_unique_tags(phrase_tag_list):
    """Create a list of unique tags"""
    unique_tags = []
    for item in phrase_tag_list:
        for tag in item:
            if tag not in unique_tags:
                unique_tags.append(tag)
    return unique_tags

def get_tag_weights(phrase_tag_list):
    """Calculate current tag weights in the repetition data"""
    unique_tags = get_unique_tags(phrase_tag_list)
    total_repetition_count = len(phrase_tag_list)
    result = dict()
    for tag in unique_tags:
        for item in phrase_tag_list:
            if tag in item:
                if tag not in result.keys():
                    result[tag] = 0
                result[tag] += 1
    for tag, reps in result.iteritems():
        result[tag] = reps / float(total_repetition_count)
    return result

def print_weights(sorted_diff, history_length, limit=None):
    """Print the calculated weights"""
    out = ""
    list_range = sorted_diff
    if limit is not None:
        list_range = sorted_diff[:limit]

    for item in list_range:
        additional_reps = history_length * item[1]
        out += "%s:%d " % (item[0], math.ceil(additional_reps) * (-1))
    print "Categories that need more repetitions:"
    print out

def main():
    """main"""
    data = get_data()
    current_weights = get_tag_weights(data)
    target_weights = CONFIG['tag_weights']
    
    diff_dict = dict()
    for tag, value in target_weights.iteritems():
        if tag in current_weights.keys():
            diff_dict[tag] = target_weights[tag] - current_weights[tag]
        else:
            diff_dict[tag] = target_weights[tag]

    sorted_diff = sorted(diff_dict.items(), key=operator.itemgetter(1))
    sorted_diff.reverse()
    
    if len(sorted_diff) > 3:
        limit = 3
    else:
        limit = None
    print_weights(sorted_diff, CONFIG['history_length'], limit=limit)


if __name__ == '__main__':
    main()
